package Vistas;

import Entidades.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ViewConsultarInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewConsultarInventario1
     */
    public ViewConsultarInventario() {
        initComponents();
        cargarTabla();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jBSalir = new javax.swing.JButton();
        jRBNombre = new javax.swing.JRadioButton();
        jRBCategoria = new javax.swing.JRadioButton();
        jTFNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCBCategoria = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        Botones.add(jRBNombre);
        jRBNombre.setText("Nombre");
        jRBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNombreActionPerformed(evt);
            }
        });

        Botones.add(jRBCategoria);
        jRBCategoria.setText("Categoria");
        jRBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCategoriaActionPerformed(evt);
            }
        });

        jTFNombre.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Inventario");

        jCBCategoria.setEnabled(false);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTDatos.setEnabled(false);
        jScrollPane1.setViewportView(jTDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBNombre)
                                    .addComponent(jRBCategoria))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBBuscar)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBCategoria)
                    .addComponent(jBBuscar))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jBSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jRBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNombreActionPerformed
        jTFNombre.setEnabled(true);
        jCBCategoria.setEnabled(false);
    }//GEN-LAST:event_jRBNombreActionPerformed

    private void jRBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCategoriaActionPerformed
        jTFNombre.setEnabled(false);
        jCBCategoria.setEnabled(true);
    }//GEN-LAST:event_jRBCategoriaActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void cargarTabla() {
        if(jRBNombre.isSelected()){
            String colum[]={"PRODUCTO","DESCRIPCION","PRECIO"};///titulo tabla(columnas)stock agregar
            Vista_FraveMAX.productos/*variable arraylist detalles ventas*/=Vista_FraveMAX.prodD.buscarNombre(jTFNombre.getText());////obtener detalle ventas base de datos
            String datos[][]=new String[Vista_FraveMAX.productos.size()]/*cantidad de filas(todas las ventas)*/[3]/*cantidad de columnas titulo(linea 89)*/;
            int i=0;
            for (Producto consultarinventario : Vista_FraveMAX.productos) {///guardar datos obtenidos en la tabla
                ///cargando datos matriz(tabla)
                datos[i][0]=consultarinventario.getNombre();
                datos[i][1]=consultarinventario.getDescripcion();
                datos[i][2]=consultarinventario.getPrecioActual()+"";
            i++;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));///insertar datos a la talba
        }else if(jRBCategoria.isSelected()){
            String colum[]={"PRODUCTO","DESCRIPCION","PRECIO"};///titulo tabla(columnas)stock agregar
            Vista_FraveMAX.productos/*variable arraylist detalles ventas*/=Vista_FraveMAX.prodD.buscarCategoria((String)jCBCategoria.getSelectedItem());////obtener detalle ventas base de datos
            String datos[][]=new String[Vista_FraveMAX.productos.size()]/*cantidad de filas(todas las ventas)*/[3]/*cantidad de columnas titulo(linea 89)*/;
            int i=0;
            for (Producto consultarinventario : Vista_FraveMAX.productos) {///guardar datos obtenidos en la tabla
                ///cargando datos matriz(tabla)
                datos[i][0]=consultarinventario.getNombre();
                datos[i][1]=consultarinventario.getDescripcion();
                datos[i][2]=consultarinventario.getPrecioActual()+"";
            i++;
            }
            jTDatos.setModel(new DefaultTableModel(datos,colum));///insertar datos a la talba
        } else {
         String colum[]={"PRODUCTO","DESCRIPCION","PRECIO"};///titulo tabla(columnas)stock agregar
        Vista_FraveMAX.productos/*variable arraylist detalles ventas*/=Vista_FraveMAX.prodD.productos();////obtener detalle ventas base de datos
        String datos[][]=new String[Vista_FraveMAX.productos.size()]/*cantidad de filas(todas las ventas)*/[3]/*cantidad de columnas titulo(linea 89)*/;
        int i=0;
        for (Producto consultarinventario : Vista_FraveMAX.productos) {///guardar datos obtenidos en la tabla
            
   
            ///cargando datos matriz(tabla)
          
            datos[i][0]=consultarinventario.getNombre();
            datos[i][1]=consultarinventario.getDescripcion();
            datos[i][2]=consultarinventario.getPrecioActual()+"";
            i++;
        }
        jTDatos.setModel(new DefaultTableModel(datos,colum));///insertar datos a la talba
      
    }}
    
    private void cargarCategorias (){
        String categorias[]=new String[Vista_FraveMAX.productos.size()];
        int i=0;
        boolean p=false;
        categorias[i]=Vista_FraveMAX.productos.get(i).getCategoria();
        i++;
        for (Producto prod:Vista_FraveMAX.productos) {
            for (int j = 0; j < i; j++) {
                if(categorias[j].equals(prod.getCategoria())){
                   p=true;
                }else{
                    p=false;
                }
            }
            if(!p){
                categorias[i]=prod.getCategoria();
                i++;
            }
        }
        for (int j = 0; j < i; j++) {
            jCBCategoria.addItem(categorias[j]);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBCategoria;
    private javax.swing.JRadioButton jRBNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
