/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author matia
 */
public class viewElimCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewElimCliente
     */
    public viewElimCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextTel = new javax.swing.JTextField();
        jBotBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextDom = new javax.swing.JTextField();
        jBotElim = new javax.swing.JButton();
        jBotSalir = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ELIMINAR CLIENTE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese el telefono del cliente a eliminar:");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelActionPerformed(evt);
            }
        });
        jTextTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelKeyTyped(evt);
            }
        });

        jBotBuscar.setText("Buscar");
        jBotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });
        jTextNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Domicilio:");

        jTextDom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDomActionPerformed(evt);
            }
        });
        jTextDom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDomKeyTyped(evt);
            }
        });

        jBotElim.setText("Eliminar");
        jBotElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotElimActionPerformed(evt);
            }
        });

        jBotSalir.setText("Salir");
        jBotSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(jTextDom, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotElim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotBuscar)
                    .addComponent(jBotSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotBuscar))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotSalir)
                    .addComponent(jBotElim))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelActionPerformed

    private void jTextTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelKeyTyped
        if((evt.getKeyChar()<48||evt.getKeyChar()>57)&&evt.getKeyChar()!=8){
            JOptionPane.showMessageDialog(this, "Igresar solo numeros","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            jTextTel.requestFocus();
        }
    }//GEN-LAST:event_jTextTelKeyTyped

    private void jBotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotBuscarActionPerformed
        boolean msj=false;
            msj=verificarCampos(jTextTel);
        if(!msj){
                Vista_FraveMAX.clien=Vista_FraveMAX.cliD.buscarTelefonoEliminar(jTextTel.getText());
        }
        if(Vista_FraveMAX.clien!=null && !msj){
            jTextTel.setText(Vista_FraveMAX.clien.getTelefono()+"");
            jTextNom.setText(Vista_FraveMAX.clien.getNombre());
            jTextDom.setText(Vista_FraveMAX.clien.getDomicilio());
        }else{
            JOptionPane.showMessageDialog(null, "Cliente no encontrado");
            Limpiar();
        }    
    }//GEN-LAST:event_jBotBuscarActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jTextNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomKeyTyped
        if(jTextNom.isEditable()){
            verificar(evt,jTextNom);
        }
    }//GEN-LAST:event_jTextNomKeyTyped

    private void jTextDomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDomActionPerformed

    private void jTextDomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDomKeyTyped

    private void jBotElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotElimActionPerformed
        if(!verificarCampos(jTextTel)){
            Vista_FraveMAX.cliD.eliminarCliente(Vista_FraveMAX.clien.getIdCliente());
            Limpiar();
            
        }
    }//GEN-LAST:event_jBotElimActionPerformed

    private void jBotSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBotSalirActionPerformed

    
    private void verificar(java.awt.event.KeyEvent evt,javax.swing.JTextField tx){
        if((evt.getKeyChar()<65||evt.getKeyChar()>90)&&(evt.getKeyChar()<97||evt.getKeyChar()>122)&&evt.getKeyChar()!=8&&evt.getKeyChar()!=32){
            JOptionPane.showMessageDialog(this, "Igresar solo letras","Advertencia",JOptionPane.WARNING_MESSAGE);
            evt.consume();
            tx.requestFocus();
        }
    }
    
    private boolean verificarCampos(javax.swing.JTextField tx){
        if(tx.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Completar Campo");
            tx.requestFocus();
            return true;
        }else{return false;}
    }

    private void Limpiar() {
        jTextNom.setText("");
        jTextDom.setText("");
        jTextTel.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotBuscar;
    private javax.swing.JButton jBotElim;
    private javax.swing.JButton jBotSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextDom;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextTel;
    // End of variables declaration//GEN-END:variables
}
