package Vistas;

import Entidades.DetalleVenta;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vega Alberto
 */
public class ViewConsultarVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarVentas
     */
    public ViewConsultarVentas() {
        super("VENTAS");
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();

        setResizable(true);

        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTDatos.setEnabled(false);
        jScrollPane1.setViewportView(jTDatos);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void cargarTabla(){
        String colum[]={"VENTA","FECHA","CLIENTE","TELEFONO","PRODUCTO","DESCRIPCION","PRECIO"};///titulo tabla(columnas)
        Vista_FraveMAX.detventas/*variable arraylist detalles ventas*/=Vista_FraveMAX.detVenD.detallesDeVenta();////obtener detalle ventas base de datos
        String datos[][]=new String[Vista_FraveMAX.detventas.size()]/*cantidad de filas(todas las ventas)*/[7]/*cantidad de columnas titulo(linea 89)*/;
        int i=0;
        for (DetalleVenta detventa : Vista_FraveMAX.detventas) {///guardar datos obtenidos en la tabla
            detventa.setProducto(Vista_FraveMAX.prodD.buscarID(detventa.getProducto().getIdProducto()));///completar datos objeto producto
            detventa.setVenta(Vista_FraveMAX.ventD.buscarID(detventa.getVenta().getIdVenta()));///completar datos objeto venta
            detventa.getVenta().setCliente(Vista_FraveMAX.cliD.buscarID(detventa.getVenta().getCliente().getIdCliente()));///completar datos objeto cliente
            ///cargando datos matriz(tabla)
            datos[i][0]=detventa.getVenta().getIdVenta()+"";
            datos[i][1]=detventa.getVenta().getFecha().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            datos[i][2]=detventa.getVenta().getCliente().getNombre();
            datos[i][3]=detventa.getVenta().getCliente().getTelefono();
            datos[i][4]=detventa.getProducto().getNombre();
            datos[i][5]=detventa.getProducto().getDescripcion();
            datos[i][6]=detventa.getProducto().getPrecioActual()+"";
            i++;
        }
        jTDatos.setModel(new DefaultTableModel(datos,colum));///insertar datos a la talba
        Vista_FraveMAX.detventas=null;///limpiar detventas
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
